import {test, expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import path from 'node:path'
test('edits merged date history and keeps shared outstanding across dates', async ({page, request}) => {
 const root = process.env.TASKTRACE_LOCAL_TEST_DIR
 test.skip(!root, 'Requires isolated local instance')
 const session = JSON.parse(readFileSync(path.join(root!, 'data/local-session.json'), 'utf8').replace(/^\uFEFF/, ''))
 const base = readFileSync(path.join(root!, 'data/local-config.yml'), 'utf8').match(/publicurl: "(http:\/\/127\.0\.0\.1:\d+)\/"/)![1]
 const headers = {Authorization: 'Bearer ' + session.token}
 const project = await (await request.post(base+'/api/v2/projects', {headers, data: {title:'日期与遗留事项验收'}})).json()
 const task = await (await request.post(`${base}/api/v2/projects/${project.id}/tasks`, {headers, data: {title:'共享事项测试'}})).json()
 const attachment = await (await request.post(`${base}/api/v2/tasks/${task.id}/attachments`, {headers, multipart: {files: {name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6AAAAAElFTkSuQmCC','base64')}}})).json()
 for(const text of ['上午进展','下午进展']) await request.post(`${base}/api/v2/tasks/${task.id}/comments`, {headers,data:{comment:`<h3>每日进展 · 2026-09-16</h3><p>${text}</p><p><strong>遗留问题 / 下一步</strong></p><p>旧遗留一<br>旧遗留二</p><img src="/api/v1/tasks/${task.id}/attachments/${attachment.success[0].id}">`}})
 await page.goto(`${base}/tasks/${task.id}#tasktrace-local=`+encodeURIComponent(JSON.stringify(session)))
 const form=page.locator('.daily-progress')
 const shared=form.getByRole('region',{name:'共享遗留事项'})
 await expect(shared).toContainText('旧遗留一')
 await expect(shared).toContainText('旧遗留二')
 await shared.getByRole('textbox',{name:'新增遗留事项'}).fill('跨日期条目')
 await shared.getByRole('button',{name:'添加遗留事项'}).click()
 await expect(shared.locator('li')).toHaveCount(3)
 await form.getByLabel('记录日期').fill('2026-09-16')
 await expect(form.getByLabel('今日进展')).toHaveValue(/上午进展[\s\S]*下午进展/)
 await expect.poll(()=>form.locator('.readonly-rich-text img').first().evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0)
 await form.getByLabel('今日进展').fill('合并后修改的历史内容')
 await form.getByRole('button',{name:'保存进展',exact:true}).click()
 await expect(form.getByRole('status')).toContainText('当天进展已保存')
 await form.getByLabel('记录日期').fill('2026-09-17')
 await expect(form.getByLabel('今日进展')).toHaveValue('')
 await expect(shared).toContainText('跨日期条目')
 await form.getByLabel('今日进展').fill('尚未提交的另一天草稿')
 await form.getByLabel('记录日期').fill('2026-09-16')
 await expect(form.getByLabel('今日进展')).toHaveValue('合并后修改的历史内容')
 await form.getByLabel('记录日期').fill('2026-09-17')
 await expect(form.getByLabel('今日进展')).toHaveValue('尚未提交的另一天草稿')
 await shared.locator('li').filter({hasText:'旧遗留一'}).getByRole('button',{name:'移除'}).click()
 await expect(shared.locator('li')).toHaveCount(2)
 await page.reload()
 await expect(shared).not.toContainText('旧遗留一')
 await expect(shared).toContainText('跨日期条目')
 await form.getByLabel('记录日期').fill('2026-09-16')
 await expect(form.getByLabel('今日进展')).toHaveValue('合并后修改的历史内容')
 const comments=await (await request.get(`${base}/api/v2/tasks/${task.id}/comments`,{headers})).json()
 expect(comments.items.filter((note:{comment:string})=>note.comment.includes('data-tasktrace-merged'))).toHaveLength(1)
 expect(comments.items.find((note:{comment:string})=>note.comment.includes('data-tasktrace-merged')).comment).toContain('/attachments/')
 await page.screenshot({path:path.join(root!,'history-shared-desktop.png'),fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await page.screenshot({path:path.join(root!,'history-shared-mobile.png'),fullPage:true})
})
