import {test, expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import path from 'node:path'

test('portable launch enters workspace without login and renews the session', async ({page}) => {
 test.setTimeout(90000)
 const root = process.env.TASKTRACE_LOCAL_TEST_DIR
 test.skip(!root, 'Requires a running isolated portable test instance')
 const session = JSON.parse(readFileSync(path.join(root!, 'data/local-session.json'), 'utf8').replace(/^\uFEFF/, ''))
 const config = readFileSync(path.join(root!, 'data/local-config.yml'), 'utf8')
 const base = config.match(/publicurl: "(http:\/\/127\.0\.0\.1:\d+)\/"/)![1]
 await page.goto(base + '/#tasktrace-local=' + encodeURIComponent(JSON.stringify(session)))
 await expect(page.locator('.menu-container')).toBeVisible({timeout: 30000})
 await expect(page).not.toHaveURL(/\/login/)
 expect(new URL(page.url()).hash).toBe('')
 await page.reload()
 await expect(page.locator('.menu-container')).toBeVisible()
 await page.waitForLoadState('networkidle')
 // Expire only the browser's access token to exercise the real OAuth refresh path.
 await page.evaluate(() => {
  const current = localStorage.getItem('token')!.split('.')
  const payload = JSON.parse(atob(current[1].replace(/-/g, '+').replace(/_/g, '/')))
  payload.exp = 1
  current[1] = btoa(JSON.stringify(payload)).replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_')
  localStorage.setItem('token', current.join('.'))
 })
 await page.reload()
 await expect(page.locator('.menu-container')).toBeVisible({timeout: 30000})
 await expect(page).not.toHaveURL(/\/login/)
 expect(await page.evaluate(() => localStorage.getItem('tasktraceLocalRefresh'))).not.toBe(session.refresh_token)
 const taskTitle = 'No-login browser task ' + Date.now()
 await page.locator('.add-task-textarea').first().fill(taskTitle)
 await page.locator('.add-task-textarea').first().press('Enter')
 await expect(page.getByText(taskTitle, {exact: true}).first()).toBeVisible({timeout: 15000})
 await page.getByText(taskTitle, {exact: true}).first().click()
 const daily = page.locator('.daily-progress')
 await expect(daily).toBeVisible()
 let progressWrites = 0
 page.on('request', request => { if (/\/api\/v2\/tasks\/\d+\/comments(?:\/\d+)?$/.test(request.url()) && ['POST', 'PUT'].includes(request.method())) progressWrites++ })
 await daily.locator('summary').click()
 await daily.getByLabel('检查间隔（秒）').fill('5')
 await daily.getByLabel('检查间隔（秒）').press('Tab')
 await daily.getByLabel('今日进展', {exact: true}).fill('完成每日进展验收 <保留文本>')
 await daily.getByLabel('遗留问题 / 下一步（选填）', {exact: true}).fill('明天继续测试图片')
 await daily.getByLabel('今日进展', {exact: true}).evaluate(element => {
  const canvas = document.createElement('canvas'); canvas.width = 20; canvas.height = 20
  canvas.getContext('2d')!.fillRect(0, 0, 20, 20)
  const bytes = Uint8Array.from(atob(canvas.toDataURL().split(',')[1]), c => c.charCodeAt(0))
  const clipboard = new DataTransfer()
  clipboard.items.add(new File([bytes], 'screenshot1.png', {type: 'image/png'}))
  clipboard.items.add(new File([bytes], 'screenshot2.png', {type: 'image/png'}))
  element.dispatchEvent(new ClipboardEvent('paste', {clipboardData: clipboard, bubbles: true, cancelable: true}))
 })
 await expect(daily.locator('.progress-images img')).toHaveCount(2)
 await expect(daily.getByRole('status')).toContainText('已自动保存', {timeout: 15000})
 expect(progressWrites).toBe(1)
 await daily.getByLabel('今日进展', {exact: true}).fill('完成每日进展验收 <保留文本>，自动更新')
 await expect(page.locator('.comment').filter({hasText: '自动更新'})).toBeVisible({timeout: 15000})
 expect(progressWrites).toBe(2)
 await page.waitForTimeout(5500)
 expect(progressWrites).toBe(2)
 await page.reload()
 await expect(daily.locator('.progress-images img')).toHaveCount(2)
 await page.waitForTimeout(5500)
 expect(progressWrites).toBe(2)
 await daily.locator('summary').click()
 await expect(daily.getByLabel('检查间隔（秒）')).toHaveValue('5')
 await daily.getByLabel('启用自动保存').uncheck()
 await daily.getByLabel('遗留问题 / 下一步（选填）').fill('关闭自动保存后手动提交')
 await page.waitForTimeout(5500)
 expect(progressWrites).toBe(2)
 await daily.getByRole('button', {name: '保存进展', exact: true}).click()
 await expect(daily.getByRole('status')).toContainText('进展已保存')
 expect(progressWrites).toBe(3)
 await expect(page.locator('.comment').filter({hasText: '完成每日进展验收 <保留文本>'})).toBeVisible()
 await daily.getByLabel('今日进展', {exact: true}).fill('同一天补充第二条进展')
 await daily.getByLabel('今日进展', {exact: true}).press('Control+Enter')
 await expect(page.locator('.comment').filter({hasText: '同一天补充第二条进展'})).toBeVisible()
 await page.reload()
 await expect(page.locator('.comment').filter({hasText: '完成每日进展验收 <保留文本>'})).toBeVisible()
 await expect(page.locator('.comment').filter({hasText: '同一天补充第二条进展'})).toBeVisible()
 const pictures = page.locator('.comment').filter({hasText: '完成每日进展验收 <保留文本>'}).locator('img[data-src]')
 await expect.poll(async () => pictures.evaluateAll(nodes => nodes.filter(node => (node as HTMLImageElement).naturalWidth === 20).length)).toBe(2)
 await page.screenshot({path: path.join(root!, 'workspace.png')})
})
