// SPDX-License-Identifier: AGPL-3.0-or-later

package models

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"slices"
	"sort"
	"strings"
	"time"

	"code.vikunja.io/api/pkg/user"
	"code.vikunja.io/api/pkg/web"
	"xorm.io/xorm"
)

const taskTraceTeamMembersLinkPrefix = "tasktrace-team-members://import/"

type TaskTraceTeamMemberCandidate struct {
	Username    string `json:"username" readOnly:"true" doc:"The account's short Windows username used as the TaskTrace collaboration identity."`
	AccountName string `json:"account_name" readOnly:"true" doc:"The canonical Windows account name used when granting folder and SMB permissions."`
	DisplayName string `json:"display_name,omitempty" readOnly:"true" doc:"The display name reported by Windows when available."`
	Email       string `json:"email,omitempty" readOnly:"true" doc:"The email address reported by the Windows directory when available."`
}

type TaskTraceTeamMemberSearchResult struct {
	Candidates []TaskTraceTeamMemberCandidate `json:"candidates" readOnly:"true" doc:"Matching local or domain Windows accounts."`
}

type TaskTraceTeamMemberAccessRequest struct {
	AccountName string `json:"account_name" minLength:"1" doc:"A canonical or resolvable Windows account name."`
	Username    string `json:"username,omitempty" doc:"The account's short Windows username."`
	DisplayName string `json:"display_name,omitempty" doc:"The display name returned by Windows directory search."`
	Email       string `json:"email,omitempty" doc:"The email address returned by Windows directory search."`
	Access      string `json:"access,omitempty" enum:"read,write" default:"write" doc:"The maximum access granted through the teamData Windows share."`
}

type TaskTraceTeamMemberImportRequest struct {
	Link string `json:"link" minLength:"1" doc:"A TaskTrace team-member link generated by another team member."`
}

type TaskTraceTeamMemberFailure struct {
	Username string `json:"username" readOnly:"true" doc:"The member which could not be resolved or granted access."`
	Reason   string `json:"reason" readOnly:"true" doc:"Why this member could not be imported."`
}

type TaskTraceTeamMemberImportResult struct {
	Status      TaskTraceTeamStatus          `json:"status" readOnly:"true" doc:"The updated local collaboration status."`
	Added       []string                     `json:"added" readOnly:"true" doc:"Members whose teamData read/write access is now available."`
	SkippedSelf []string                     `json:"skipped_self" readOnly:"true" doc:"Entries matching the current user, skipped without treating them as failures."`
	Failed      []TaskTraceTeamMemberFailure `json:"failed" readOnly:"true" doc:"Members that could not be imported; valid members are still kept."`
}

type taskTraceTeamMembersLink struct {
	Schema  int      `json:"schema"`
	Members []string `json:"members"`
}

func taskTraceTeamMembershipName(value string) string {
	value = strings.TrimSpace(value)
	if at := strings.LastIndex(value, `\`); at >= 0 {
		value = value[at+1:]
	}
	if at := strings.Index(value, "@"); at > 0 {
		value = value[:at]
	}
	return strings.TrimSpace(value)
}

func taskTraceTeamMembersEqual(left, right string) bool {
	return strings.EqualFold(taskTraceTeamMembershipName(left), taskTraceTeamMembershipName(right))
}

func taskTraceTeamEncodeMembersLink(members []string) string {
	normalized := taskTraceTeamNormalizeMembers(members, "")
	b, _ := json.Marshal(taskTraceTeamMembersLink{Schema: taskTraceTeamSchema, Members: normalized})
	return taskTraceTeamMembersLinkPrefix + base64.RawURLEncoding.EncodeToString(b)
}

func taskTraceTeamDecodeMembersLink(link string) ([]string, error) {
	link = strings.TrimSpace(link)
	if !strings.HasPrefix(strings.ToLower(link), taskTraceTeamMembersLinkPrefix) {
		return nil, errors.New("无效的团队成员链接")
	}
	b, err := base64.RawURLEncoding.DecodeString(link[len(taskTraceTeamMembersLinkPrefix):])
	if err != nil {
		return nil, errors.New("无效的团队成员链接")
	}
	var parsed taskTraceTeamMembersLink
	if json.Unmarshal(b, &parsed) != nil || parsed.Schema != taskTraceTeamSchema {
		return nil, errors.New("无效的团队成员链接")
	}
	parsed.Members = taskTraceTeamNormalizeMembers(parsed.Members, "")
	if len(parsed.Members) == 0 {
		return nil, errors.New("团队成员链接中没有可导入的成员")
	}
	return parsed.Members, nil
}

func TaskTraceTeamSearchMembers(ctx context.Context, query string, quick bool) (TaskTraceTeamMemberSearchResult, error) {
	query = strings.TrimSpace(query)
	if len([]rune(query)) < 1 {
		return TaskTraceTeamMemberSearchResult{Candidates: []TaskTraceTeamMemberCandidate{}}, nil
	}
	candidates, err := taskTraceTeamSearchWindowsMembers(ctx, query, quick)
	if err != nil {
		return TaskTraceTeamMemberSearchResult{}, err
	}
	return TaskTraceTeamMemberSearchResult{Candidates: candidates}, nil
}

func taskTraceTeamUnassignedMembers(state taskTraceTeamState, candidates []string, current string) []string {
	assigned := []string{current}
	for _, binding := range state.Bindings {
		assigned = append(assigned, binding.Owner)
		assigned = append(assigned, binding.Members...)
	}
	result := []string{}
	for _, candidate := range candidates {
		found := false
		for _, member := range assigned {
			if taskTraceTeamMembersEqual(candidate, member) {
				found = true
				break
			}
		}
		if !found {
			result = append(result, candidate)
		}
	}
	sort.Slice(result, func(i, j int) bool { return strings.ToLower(result[i]) < strings.ToLower(result[j]) })
	return result
}

func TaskTraceTeamGrantMemberAccess(s *xorm.Session, a web.Auth, request TaskTraceTeamMemberAccessRequest, elevate bool) (*TaskTraceTeamStatus, error) {
	taskTraceTeamMu.Lock()
	defer taskTraceTeamMu.Unlock()
	u, err := user.GetFromAuth(a)
	if err != nil {
		return nil, err
	}
	if taskTraceTeamMembersEqual(request.AccountName, u.Username) {
		return nil, errors.New("当前用户已经拥有 teamData 权限")
	}
	access := strings.ToLower(strings.TrimSpace(request.Access))
	if access == "" {
		access = TaskTraceTeamAccessWrite
	}
	if access != TaskTraceTeamAccessRead && access != TaskTraceTeamAccessWrite {
		return nil, errors.New("teamData 权限必须是 read 或 write")
	}
	resolved, err := taskTraceTeamSetWindowsAccessWithElevation(taskTraceTeamRoot(), request.AccountName, access, elevate)
	if err != nil {
		return nil, fmt.Errorf("无法为 %s 设置 teamData 权限：%w", request.AccountName, err)
	}
	candidate := TaskTraceTeamMemberCandidate{Username: request.Username, AccountName: resolved, DisplayName: request.DisplayName, Email: request.Email}
	if candidate.Username == "" {
		candidate.Username = taskTraceTeamMembershipName(resolved)
	}
	if candidate.DisplayName != "" || candidate.Email != "" {
		if _, err := rememberTaskTraceWindowsTeamUser(s, candidate); err != nil {
			return nil, fmt.Errorf("保存协作成员资料失败：%w", err)
		}
	} else {
		ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
		defer cancel()
		if found, searchErr := taskTraceSearchTeamMembers(ctx, resolved, false); searchErr == nil {
			for _, profile := range found.Candidates {
				if taskTraceTeamMembersEqual(profile.AccountName, resolved) {
					_, _ = rememberTaskTraceWindowsTeamUser(s, profile)
					break
				}
			}
		}
	}
	state, err := taskTraceTeamLoadState()
	if err != nil {
		return nil, err
	}
	status, err := taskTraceTeamStatusLockedFast(s, a, state)
	if err == nil && len(taskTraceTeamUnassignedMembers(state, []string{resolved}, u.Username)) > 0 {
		if !slices.ContainsFunc(status.Repository.Candidates, func(member string) bool { return taskTraceTeamMembersEqual(member, resolved) }) {
			status.Repository.Candidates = append(status.Repository.Candidates, resolved)
			sort.Slice(status.Repository.Candidates, func(i, j int) bool {
				return strings.ToLower(status.Repository.Candidates[i]) < strings.ToLower(status.Repository.Candidates[j])
			})
		}
		if !slices.ContainsFunc(status.UnassignedMembers, func(member string) bool { return taskTraceTeamMembersEqual(member, resolved) }) {
			status.UnassignedMembers = append(status.UnassignedMembers, resolved)
			sort.Slice(status.UnassignedMembers, func(i, j int) bool {
				return strings.ToLower(status.UnassignedMembers[i]) < strings.ToLower(status.UnassignedMembers[j])
			})
		}
	}
	if err == nil {
		updated := false
		for index := range status.Repository.Members {
			if taskTraceTeamMembersEqual(status.Repository.Members[index].AccountName, resolved) {
				status.Repository.Members[index].Access = access
				updated = true
				break
			}
		}
		if !updated {
			status.Repository.Members = append(status.Repository.Members, TaskTraceTeamRepositoryMember{AccountName: resolved, Access: access})
		}
		sort.Slice(status.Repository.Members, func(i, j int) bool {
			return strings.ToLower(status.Repository.Members[i].AccountName) < strings.ToLower(status.Repository.Members[j].AccountName)
		})
	}
	return &status, err
}

func TaskTraceTeamRemoveMemberAccess(s *xorm.Session, a web.Auth, accountName string, elevate bool) (*TaskTraceTeamStatus, error) {
	taskTraceTeamMu.Lock()
	defer taskTraceTeamMu.Unlock()
	u, err := user.GetFromAuth(a)
	if err != nil {
		return nil, err
	}
	if taskTraceTeamMembersEqual(accountName, u.Username) {
		return nil, errors.New("不能移除当前用户的 teamData 权限")
	}
	state, err := taskTraceTeamLoadState()
	if err != nil {
		return nil, err
	}
	for _, binding := range state.Bindings {
		for _, member := range append([]string{binding.Owner}, binding.Members...) {
			if taskTraceTeamMembersEqual(accountName, member) {
				return nil, errors.New("该成员仍属于团队，请先从所有团队中移除")
			}
		}
	}
	if err := taskTraceTeamRemoveWindowsAccessWithElevation(taskTraceTeamRoot(), accountName, elevate); err != nil {
		return nil, fmt.Errorf("无法删除 %s 的 teamData 权限：%w", accountName, err)
	}
	status, err := taskTraceTeamStatusLockedFast(s, a, state)
	if err == nil {
		taskTraceTeamRemoveMemberFromStatus(&status, accountName)
	}
	return &status, err
}

func taskTraceTeamRemoveMemberFromStatus(status *TaskTraceTeamStatus, accountName string) {
	status.Repository.Candidates = slices.DeleteFunc(status.Repository.Candidates, func(member string) bool {
		return taskTraceTeamMembersEqual(member, accountName)
	})
	status.UnassignedMembers = slices.DeleteFunc(status.UnassignedMembers, func(member string) bool {
		return taskTraceTeamMembersEqual(member, accountName)
	})
	status.Repository.Members = slices.DeleteFunc(status.Repository.Members, func(member TaskTraceTeamRepositoryMember) bool {
		return taskTraceTeamMembersEqual(member.AccountName, accountName)
	})
}

func taskTraceTeamImportMemberNames(members []string, current string, grant func(string) (string, error)) (added, skipped []string, failed []TaskTraceTeamMemberFailure) {
	seen := map[string]bool{}
	for _, member := range members {
		member = strings.TrimSpace(member)
		if member == "" {
			continue
		}
		key := strings.ToLower(taskTraceTeamMembershipName(member))
		if seen[key] {
			continue
		}
		seen[key] = true
		if taskTraceTeamMembersEqual(member, current) {
			skipped = append(skipped, member)
			continue
		}
		resolved, err := grant(member)
		if err != nil {
			failed = append(failed, TaskTraceTeamMemberFailure{Username: member, Reason: err.Error()})
			continue
		}
		added = append(added, resolved)
	}
	return
}

func TaskTraceTeamImportMembers(s *xorm.Session, a web.Auth, request TaskTraceTeamMemberImportRequest) (*TaskTraceTeamMemberImportResult, error) {
	taskTraceTeamMu.Lock()
	defer taskTraceTeamMu.Unlock()
	u, err := user.GetFromAuth(a)
	if err != nil {
		return nil, err
	}
	members, err := taskTraceTeamDecodeMembersLink(request.Link)
	if err != nil {
		return nil, err
	}
	added, skipped, failed := taskTraceTeamImportMemberNames(members, u.Username, func(member string) (string, error) {
		return taskTraceTeamGrantWindowsAccess(taskTraceTeamRoot(), member)
	})
	state, err := taskTraceTeamLoadState()
	if err != nil {
		return nil, err
	}
	status, err := taskTraceTeamStatusLockedFast(s, a, state)
	if err != nil {
		return nil, err
	}
	return &TaskTraceTeamMemberImportResult{Status: status, Added: added, SkippedSelf: skipped, Failed: failed}, nil
}
